const Koa = require("koa");
const bodyParser = require("koa-bodyparser");
const userRouter = require("../router/user.router");
const handleError = require("./errorHandle");
const app = new Koa();
app.use(bodyParser());
app.use(userRouter.routes());
app.use(userRouter.allowedMethods());
app.on("error", handleError);
module.exports = app;
